name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fix Gradle Version Validation
        run: |
          mkdir -p ~/.config/flet
          echo '{"android": {"skipDependencyValidation": true}}' > ~/.config/flet/config.json
          mkdir -p android/gradle/wrapper
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip" > android/gradle/wrapper/gradle-wrapper.properties

      - name: Build Android APK
        run: |
          flet build apk
      - name: Upload Generated APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: military-schedule-apk
          path: build/apk/*.apk
